<?php
        /*************************************************************/
        /*  CHANGES TO THIS FILE WILL BE OVERWRITTEN BY THE WEB UI!  */
        /*************************************************************/
        //Generated by SWMP Settings at 2021-11-20 02:18:25
        return array
        (
            // General settings
            "lang" => "en_GB",
            "theme" => "cosmo",
            "showerrors" => 0,
            "windowtitle" => "Host: {hostname}",
            "reload" => 60,
            "debug" => 0,

            // Hide Sections (1 is shown, 0 is hidden.)

            // System Information
            "hostname" => 1,
            "ip" => 1,
            "os" => 1,
            "kernel" => 1,
            "uptime" => 1,
            "boottime" => 1,
            "cpuinfo" => 1,
            "temp" => 1,
            // RAM & Swamp
            "ram" => 1,
            "swap" => 1,
            // CPU
            "1min" => 1,
            "5min" => 1,
            "15min" => 1,
            // Network Information
            "netinfo" => 1,
            // Disk Information
            "diskinfo" => 1,
        );
        